"""
sasana.compliance.soc2 — SOC 2 Type II CC7.2 evidence report generator.

Control: CC7.2 — The entity monitors system components and the operation of
those controls on an ongoing basis to identify potential security
vulnerabilities and errors.

For AI systems this means: every model invocation is logged, the log is
tamper-evident, and anomalies (dropped events, hash mismatches) are detected.

Usage:
    from sasana.compliance.soc2 import generate_soc2_report

    report = generate_soc2_report(
        "~/.openclaw/sasana/<session_id>.jsonl",
        output_dir="./compliance_reports/",
    )
    # Writes:
    #   ./compliance_reports/<session_id>_soc2_cc72.json
    #   ./compliance_reports/<session_id>_soc2_cc72.html
    print(report["result"])  # "PASS" or "FAIL"
"""

from __future__ import annotations

import datetime
import json
from pathlib import Path
from typing import Optional

from sasana.compliance import load_session, verify_session

CONTROL_ID = "CC7.2"
CONTROL_NAME = "System Monitoring"
FRAMEWORK = "SOC 2 Type II"
STANDARD_VERSION = "AICPA 2017 Trust Services Criteria"


def generate_soc2_report(
    session_jsonl: str | Path,
    output_dir: Optional[str | Path] = None,
) -> dict:
    path = Path(session_jsonl).expanduser()
    events = load_session(path)
    verification = verify_session(events)

    generated_at = datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
    session_id = verification["session_id"] or path.stem

    first_evt = events[0] if events else {}
    last_evt = events[-1] if events else {}
    session_start = first_evt.get("timestamp", "")
    session_end = last_evt.get("timestamp", "")

    event_type_counts: dict[str, int] = {}
    for evt in events:
        et = evt.get("event_type", "UNKNOWN")
        event_type_counts[et] = event_type_counts.get(et, 0) + 1

    result = "PASS" if verification["intact"] else "FAIL"

    report = {
        "schema_version": "1.0",
        "framework": FRAMEWORK,
        "standard": STANDARD_VERSION,
        "control_id": CONTROL_ID,
        "control_name": CONTROL_NAME,
        "generated_at": generated_at,
        "session_id": session_id,
        "source_file": str(path),
        "result": result,
        "evidence_class": verification["evidence_class"],
        "event_count": verification["event_count"],
        "log_drop_count": verification["log_drop_count"],
        "hash_chain_verified": verification["intact"],
        "root_hash": verification["root_hash"],
        "session_start": session_start,
        "session_end": session_end,
        "event_type_summary": event_type_counts,
        "integrity_errors": verification["errors"],
        "attestation": (
            "This evidence package was generated by Sasana v1.0.0. "
            "The hash chain integrity has been cryptographically verified. "
            f"Result: {result}."
        ),
    }

    out_dir = Path(output_dir).expanduser() if output_dir else path.parent
    out_dir.mkdir(parents=True, exist_ok=True)
    stem = f"{session_id}_soc2_cc72"

    json_path = out_dir / f"{stem}.json"
    json_path.write_text(json.dumps(report, indent=2))

    html_path = out_dir / f"{stem}.html"
    html_path.write_text(_render_soc2_html(report))

    report["json_path"] = str(json_path)
    report["html_path"] = str(html_path)
    return report


def _render_soc2_html(r: dict) -> str:
    badge_color = "#22c55e" if r["result"] == "PASS" else "#ef4444"
    badge_text = r["result"]
    ev_rows = "\n".join(
        f"<tr><td>{et}</td><td>{count}</td></tr>"
        for et, count in sorted(r["event_type_summary"].items())
    )
    error_section = ""
    if r["integrity_errors"]:
        items = "\n".join(f"<li>{e}</li>" for e in r["integrity_errors"])
        error_section = f"<h3>Integrity Errors</h3><ul class='errors'>{items}</ul>"

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>SOC 2 CC7.2 Evidence — {r["session_id"]}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
         max-width: 900px; margin: 40px auto; padding: 0 20px; color: #1e293b; }}
  h1   {{ font-size: 1.5rem; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px; }}
  h2   {{ font-size: 1.1rem; color: #475569; margin-top: 28px; }}
  h3   {{ font-size: 1rem; color: #475569; }}
  .badge {{ display: inline-block; background: {badge_color}; color: #fff;
            font-weight: 700; padding: 4px 14px; border-radius: 4px;
            font-size: 1.1rem; vertical-align: middle; }}
  table  {{ width: 100%; border-collapse: collapse; margin: 12px 0; }}
  th, td {{ text-align: left; padding: 8px 12px; border: 1px solid #e2e8f0; }}
  th     {{ background: #f8fafc; font-weight: 600; }}
  .mono  {{ font-family: 'SF Mono', 'Fira Code', monospace; font-size: 0.85rem;
            word-break: break-all; }}
  .errors li {{ color: #ef4444; margin: 4px 0; }}
  footer  {{ margin-top: 40px; color: #94a3b8; font-size: 0.8rem; border-top: 1px solid #e2e8f0; padding-top: 12px; }}
</style>
</head>
<body>
<h1>SOC 2 Type II — CC7.2 Evidence Package &nbsp; <span class="badge">{badge_text}</span></h1>
<p><strong>Standard:</strong> {r["standard"]}<br>
<strong>Control:</strong> {r["control_id"]} — {r["control_name"]}<br>
<strong>Generated:</strong> {r["generated_at"]}</p>

<h2>Session Summary</h2>
<table>
  <tr><th>Session ID</th><td class="mono">{r["session_id"]}</td></tr>
  <tr><th>Evidence Class</th><td><strong>{r["evidence_class"]}</strong></td></tr>
  <tr><th>Hash Chain Verified</th><td>{"✅ Yes" if r["hash_chain_verified"] else "❌ No"}</td></tr>
  <tr><th>Event Count</th><td>{r["event_count"]}</td></tr>
  <tr><th>Log Drop Count</th><td>{r["log_drop_count"]}</td></tr>
  <tr><th>Session Start</th><td>{r["session_start"]}</td></tr>
  <tr><th>Session End</th><td>{r["session_end"]}</td></tr>
  <tr><th>Root Hash</th><td class="mono">{r["root_hash"] or "N/A"}</td></tr>
</table>

<h2>Event Type Summary</h2>
<table>
  <tr><th>Event Type</th><th>Count</th></tr>
  {ev_rows}
</table>

{error_section}

<h2>Attestation</h2>
<p>{r["attestation"]}</p>

<footer>Generated by Sasana v1.0.0 &middot; Source: {r["source_file"]}</footer>
</body>
</html>"""
